app/main/forms.py
from flask_wtf import FlaskForm
from govuk_frontend_wtf.wtforms_widgets import GovRadioInput, GovSubmitInput
from wtforms.fields import RadioField, SubmitField
from wtforms.validators import InputRequired


class CookiesForm(FlaskForm):
    functional = RadioField(
        "Do you want to accept functional cookies?",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Select yes if you want to accept functional cookies")],
        choices=[("no", "No"), ("yes", "Yes")],
        default="no",
    )
    analytics = RadioField(
        "Do you want to accept analytics cookies?",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Select yes if you want to accept analytics cookies")],
        choices=[("no", "No"), ("yes", "Yes")],
        default="no",
    )
    save = SubmitField("Save cookie settings", widget=GovSubmitInput())

app/__init__.py
from flask import Flask
from flask_assets import Bundle, Environment
from flask_compress import Compress
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_talisman import Talisman
from flask_wtf.csrf import CSRFProtect
from govuk_frontend_wtf.main import WTFormsHelpers
from jinja2 import ChoiceLoader, PackageLoader, PrefixLoader

from config import Config

assets = Environment()
compress = Compress()
csrf = CSRFProtect()
limiter = Limiter(key_func=get_remote_address, default_limits=["2 per second", "60 per minute"])
talisman = Talisman()


def create_app(config_class=Config):
    app = Flask(__name__, static_url_path="/assets")
    app.config.from_object(config_class)
    app.jinja_env.lstrip_blocks = True
    app.jinja_env.trim_blocks = True
    app.jinja_loader = ChoiceLoader(
        [
            PackageLoader("app"),
            PrefixLoader(
                {
                    "govuk_frontend_jinja": PackageLoader("govuk_frontend_jinja"),
                    "govuk_frontend_wtf": PackageLoader("govuk_frontend_wtf"),
                }
            ),
        ]
    )

    # Set content security policy
    csp = {
        "default-src": "'self'",
        "script-src": [
            "'self'",
            "'sha256-+6WnXIl4mbFTCARd8N3COQmT3bJJmo32N8q8ZSQAIcU='",
            "'sha256-l1eTVSK8DTnK8+yloud7wZUqFrI0atVo6VlC6PJvYaQ='",
        ],
    }

    # Initialise app extensions
    assets.init_app(app)
    compress.init_app(app)
    csrf.init_app(app)
    limiter.init_app(app)
    talisman.init_app(app, content_security_policy=csp)
    WTFormsHelpers(app)

    # Create static asset bundles
    css = Bundle("src/css/*.css", filters="cssmin", output="dist/css/custom-%(version)s.min.css")
    js = Bundle("src/js/*.js", filters="jsmin", output="dist/js/custom-%(version)s.min.js")
    if "css" not in assets:
        assets.register("css", css)
    if "js" not in assets:
        assets.register("js", js)

    # Register blueprints
    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, template_folder="../templates/main")

from app.main import routes  # noqa: E402,F401

app/main/routes.py
from flask import flash, json, make_response, redirect, render_template, request
from flask_wtf.csrf import CSRFError
from werkzeug.exceptions import HTTPException

from app.main import bp
from app.main.forms import CookiesForm


@bp.route("/", methods=["GET"])
def index():
    return render_template("index.html")


@bp.route("/accessibility", methods=["GET"])
def accessibility():
    return render_template("accessibility.html")


@bp.route("/cookies", methods=["GET", "POST"])
def cookies():
    form = CookiesForm()
    # Default cookies policy to reject all categories of cookie
    cookies_policy = {"functional": "no", "analytics": "no"}

    if form.validate_on_submit():
        # Update cookies policy consent from form data
        cookies_policy["functional"] = form.functional.data
        cookies_policy["analytics"] = form.analytics.data

        # Create flash message confirmation before rendering template
        flash("You’ve set your cookie preferences.", "success")

        # Create the response so we can set the cookie before returning
        response = make_response(render_template("cookies.html", form=form))

        # Set cookies policy for one year
        response.set_cookie("cookies_policy", json.dumps(cookies_policy), max_age=31557600)
        return response
    elif request.method == "GET":
        if request.cookies.get("cookies_policy"):
            # Set cookie consent radios to current consent
            cookies_policy = json.loads(request.cookies.get("cookies_policy"))
            form.functional.data = cookies_policy["functional"]
            form.analytics.data = cookies_policy["analytics"]
        else:
            # If conset not previously set, use default "no" policy
            form.functional.data = cookies_policy["functional"]
            form.analytics.data = cookies_policy["analytics"]
    return render_template("cookies.html", form=form)


@bp.route("/privacy", methods=["GET"])
def privacy():
    return render_template("privacy.html")


@bp.app_errorhandler(HTTPException)
def http_exception(error):
    return render_template(f"{error.code}.html"), error.code


@bp.app_errorhandler(CSRFError)
def csrf_error(error):
    flash("The form you were submitting has expired. Please try again.")
    return redirect(request.full_path)

app/templates/base.html
{% extends 'govuk_frontend_jinja/template.html' %}

{%- from 'govuk_frontend_jinja/components/cookie-banner/macro.html' import govukCookieBanner-%}
{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary-%}
{%- from 'govuk_frontend_jinja/components/notification-banner/macro.html' import govukNotificationBanner -%}
{%- from 'govuk_frontend_jinja/components/phase-banner/macro.html' import govukPhaseBanner -%}

{% set assetPath = url_for('static', filename='').rstrip('/') %}

{% block pageTitle %}{{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% block head %}
  <meta name="description" content="{{config['SERVICE_NAME']}}">
  <meta name="keywords" content="GOV.UK, govuk, gov, government, uk, frontend, ui, user interface, jinja, python, flask, port, template, templating, macro, component, design system, html, forms, wtf, wtforms, widget, widgets, demo, example">
  <meta name="author" content="{{config['DEPARTMENT_NAME']}}">
  <!--[if gt IE 8]><!--><link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='govuk-frontend-4.2.0.min.css') }}" /><!--<![endif]-->
  <!--[if IE 8]><link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='govuk-frontend-ie8-4.2.0.min.css') }}" /><![endif]-->
  {% assets "css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{% endblock %}

{% block bodyStart %}
  {% if "cookies_policy" not in request.cookies %}
    {% set html %}
      <p class="govuk-body">We use some essential cookies to make this service work.</p>
      <p class="govuk-body">We’d like to set additional cookies so we can remember your settings, understand how people use the service and make improvements.</p>
    {% endset %}

    {% set acceptHtml %}
      <p class="govuk-body">You’ve accepted additional cookies. You can <a class="govuk-link" href="{{ url_for('main.cookies') }}">change your cookie settings</a> at any time.</p>
    {% endset %}

    {% set rejectHtml %}
      <p class="govuk-body">You’ve rejected additional cookies. You can <a class="govuk-link" href="{{ url_for('main.cookies') }}">change your cookie settings</a> at any time.</p>
    {% endset %}

    {{ govukCookieBanner({
      'ariaLabel': "Cookies on " + config['SERVICE_NAME'],
      'attributes': {
        'id': "cookie-banner"
      },
      'messages': [
        {
          'attributes': {
            'id': "default-message"
          },
          'headingText': "Cookies on " + config['SERVICE_NAME'],
          'html': html,
          'actions': [
            {
              'attributes': {
                'id': "accept-cookies"
              },
              'text': "Accept additional cookies",
              'type': "button",
              'name': "cookies",
              'value': "accept"
            },
            {
              'attributes': {
                'id': "reject-cookies"
              },
              'text': "Reject additional cookies",
              'type': "button",
              'name': "cookies",
              'value': "reject"
            },
            {
              'text': "View cookies",
              'href': url_for('main.cookies')
            }
          ]
        },
        {
          'attributes': {
            'id': "accepted-message"
          },
          'html': acceptHtml,
          'role': "alert",
          'hidden': true,
          'actions': [
            {
              'attributes': {
                'id': "accepted-hide"
              },
              'text': "Hide this message"
            }
          ]
        },
        {
          'attributes': {
            'id': "rejected-message"
          },
          'html': rejectHtml,
          'role': "alert",
          'hidden': true,
          'actions': [
            {
              'attributes': {
                'id': "rejected-hide"
              },
              'text': "Hide this message"
            }
          ]
        }
      ]
    }) }}
  {% endif %}
{% endblock %}

{% block header %}
  {{ govukHeader({
    'homepageUrl': url_for('main.index'),
    'serviceName': config['SERVICE_NAME'],
    'serviceUrl': url_for('main.index')
  }) }}
{% endblock %}

{% block beforeContent %}
  {{ govukPhaseBanner({
    'tag': {
      'text': config['SERVICE_PHASE']
    },
    'html': 'This is a new service – your <a class="govuk-link" href="mailto:' + config['CONTACT_EMAIL'] +'?subject=Feedback">feedback</a> will help us to improve it.'
  }) }}
{% endblock %}

{% block content %}
  {% if form and form.errors %}
    {{ govukErrorSummary(wtforms_errors(form)) }}
  {% endif %}

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
          {{ govukNotificationBanner({'type': category, 'html': message}) }}
      {% endfor %}
    {% endif %}
  {% endwith %}
{% endblock %}

{% block footer %}
  {{ govukFooter({
    'meta': {
      'items': [
        {
          'href': url_for('main.accessibility'),
          'text': "Accessibility"
        },
        {
          'href': url_for('main.cookies'),
          'text': "Cookies"
        },
        {
            'href': url_for('main.privacy'),
            'text': "Privacy"
          }
      ],
      'html': 'Built by <a href="' + config['DEPARTMENT_URL'] +'" class="govuk-footer__link">' + config['DEPARTMENT_NAME'] + '</a>'
    }
  }) }}
{% endblock %}

{% block bodyEnd %}
  <!--[if gt IE 8]><!-->
  <script src="{{ url_for('static', filename='govuk-frontend-4.2.0.min.js') }}"> </script>
  <script>window.GOVUKFrontend.initAll()</script>
  <!--<![endif]-->
  {% assets "js" %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
{% endblock %}

app/templates/main/429.html
{% extends "base.html" %}

{% block pageTitle %}Too many requests – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% set mainClasses = "govuk-main-wrapper--l" %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Sorry, there is a problem</h1>
        <p class="govuk-body">There have been too many attempts to access this page.</p>
        <p class="govuk-body">Try again later.</p>
    </div>
</div>
{% endblock %}

app/templates/main/503.html
{% extends "base.html" %}

{% block pageTitle %}Sorry, the service is unavailable – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% set mainClasses = "govuk-main-wrapper--l" %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Sorry, the service is unavailable</h1>
        <p class="govuk-body">You will be able to use the service from 9am on Monday 19&nbsp;November&nbsp;2018.</p>
    </div>
</div>
{% endblock %}

app/templates/main/cookies.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}
{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}

{% block pageTitle %}{%- if form.errors %}Error: {% endif -%}Cookies – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <h1 class="govuk-heading-l">Cookies</h1>
    <p class="govuk-body">Cookies are small files saved on your phone, tablet or computer when you visit a website.
    </p>
    <p class="govuk-body">We use cookies to make {{config['SERVICE_NAME']}} work and collect information about how you use our
      service.</p>

    <h2 class="govuk-heading-m">Essential cookies</h2>
    <p class="govuk-body">Essential cookies keep your information secure while you use {{config['SERVICE_NAME']}}. We do not need
      to ask permission to use them.</p>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'cookie_policy'}, {'text': 'Saves your cookie consent settings'}, {'text': '1 year'}],
          [{'text': 'session'}, {'text': 'Temporary storage'}, {'text': 'Session'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Functional cookies</h2>
    <p class="govuk-body">Functional cookies allow you to take advantage of some functionality, for example remembering
      settings between visits. The service will work without them.</p>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'foo'}, {'text': 'bar'}, {'text': 'baz'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Analytics cookies</h2>
    <p class="govuk-body">With your permission, we use Google Analytics to collect data about how you use {{config['SERVICE_NAME']}}. This
      information helps us to improve our service.</p>
    <p class="govuk-body">Google is not allowed to use or share our analytics data with anyone.</p>
    <p class="govuk-body">Google Analytics stores anonymised information about:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>how you got to {{config['SERVICE_NAME']}}</li>
      <li>the pages you visit on {{config['SERVICE_NAME']}} and how long you spend on them</li>
      <li>any errors you see while using {{config['SERVICE_NAME']}}</li>
    </ul>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'foo'}, {'text': 'bar'}, {'text': 'baz'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Change your cookie settings</h2>
    <form action="" method="post" novalidate>
      {{ form.csrf_token }}
      {{ form.functional }}
      {{ form.analytics }}
      {{ form.save }}
    </form>
  </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block beforeContent %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">Hello, World!</h1>
    <p class="govuk-body-l">This is a template <a href="https://flask.palletsprojects.com" class="govuk-link">Flask</a>
      app using the <a href="https://frontend.design-system.service.gov.uk/" class="govuk-link">GOV.UK Frontend</a> and
      <a href="https://design-system.service.gov.uk/" class="govuk-link">GOV.UK Design System</a> which is designed to
      get a new project started quicker.
    </p>
    <p class="govuk-body">It is also a reference implementation of two core packages:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li><a class="govuk-link" href="https://github.com/LandRegistry/govuk-frontend-jinja">GOV.UK Frontend Jinja</a>
        which provides Jinja macros of GOV.UK components</li>
      <li><a class="govuk-link" href="https://github.com/LandRegistry/govuk-frontend-wtf">GOV.UK Frontend WTForms</a>
        which provides WTForms widgets to integrate the above Jinja macros into form generation and validation</li>
    </ul>
    <p class="govuk-body">The app is provided intentionally bare, with just the essential parts that all services need,
      such as error pages, accessibility statement, cookie banner, cookie page and privacy notice.</p>

    <h2 class="govuk-heading-m">Features</h2>
    <p class="govuk-body">A number of other packages are used to provide the features listed below with sensible and
      best-practice defaults:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>Asset management</li>
      <li>Cache busting</li>
      <li>Form generation and validation</li>
      <li>Form error handing</li>
      <li>Flash messages</li>
      <li>CSRF protection</li>
      <li>HTTP security headers</li>
      <li>Content Security Policy (CSP)</li>
      <li>Response compression</li>
      <li>Rate limiting</li>
    </ul>

    <h2 class="govuk-heading-m">Getting started</h2>
    <h3 class="govuk-heading-s">Create a new repository</h3>
    <p class="govuk-body"><a class="govuk-link"
        href="https://github.com/LandRegistry/govuk-frontend-flask/generate">Generate a new repository</a> using this
      template, with the same directory structure and files. Then clone a local copy of your newly created repository.
    </p>
    <h3 class="govuk-heading-s">Create venv and install requirements</h3>
    <p class="govuk-body">Run the following commands in your terminal, in the directory you cloned the app into:</p>
    <p class="govuk-body">
      <code>
        python3 -m venv venv<br>
        source venv/bin/activate<br>
        pip3 install -r requirements.txt ; pip3 install -r requirements_dev.txt
      </code>
    </p>
    <h3 class="govuk-heading-s">Get GOV.UK Frontend assets</h3>
    <p class="govuk-body">For convenience a shell script has been provided to download and extract the GOV.UK Frontend
      distribution assets. In your terminal run:</p>
    <p class="govuk-body"><code>./build.sh</code></p>
    <h3 class="govuk-heading-s">Set local environment variables</h3>
    <p class="govuk-body">In the <code>.flaskenv</code> file you will find a number of environment variables. These are
      injected as global variables into the app and pre-populated into page templates as appropriate. Enter your
      specific information for the following:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>CONTACT_EMAIL</li>
      <li>CONTACT_PHONE</li>
      <li>DEPARTMENT_NAME</li>
      <li>DEPARTMENT_URL</li>
      <li>SERVICE_NAME</li>
      <li>SERVICE_PHASE</li>
      <li> SERVICE_URL</li>
    </ul>
    <h3 class="govuk-heading-s">Run the app</h3>
    <p class="govuk-body">In your terminal run:</p>
    <p class="govuk-body"><code>flask run</code></p>
    <p class="govuk-body">You should now have the app running on http://localhost:5000/</p>

    <h2 class="govuk-heading-m">Documentation</h2>
    <p class="govuk-body">Detailed documentation on the features listed above and the next steps to start building out your app on top of this template is on <a class="govuk-link"
        href="https://github.com/LandRegistry/govuk-frontend-flask#readme">GitHub</a></p>
  </div>
</div>
{% endblock %}

app/templates/main/privacy.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}

{% block pageTitle %}Privacy notice – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        {{ super() }}
        <h1 class="govuk-heading-xl">Privacy notice</h1>
    </div>
</div>
{% endblock %}